color = input ("Enter a color ")
noun = input ("Enter a plural noun ")
celebrity = input ("Enter a celebrity name ")
print("Roses are "+color+"")
print(""+noun+" are blue")
print("I love "+celebrity+"")